[package]
name = "mira-cli"
version = "0.1.0"
authors = ["Rsplwe <i@rsplwe.com>", "Scallop Ye <yescallop@gmail.com>"]
edition = "2018"

[dependencies]
mira-core = { path = "../mira-core" }
tokio = { version = "0.2", features = ["macros", "tcp", "dns", "stream", "time", "io-util"] }